### Paso 1: Obtener los datos de la BD

In [1]:
import sys
import os
import numpy as np

In [2]:
project_root = os.getcwd() #give us the actual directory

In [3]:
# Obtener el directorio padre de project_root to register credenciales_sqlserver.py
base_dir = os.path.abspath(os.path.join(project_root, ".."))
print(base_dir)
# Add to sys.path if not already added
if base_dir not in sys.path:
    sys.path.append(base_dir)
print(sys.path)

/Users/jayarza/Developer/Master Data Science/TFM/Proyecto_Git/TFM_GroupC_KS24-25
['/opt/anaconda3/envs/TFM_Project/lib/python312.zip', '/opt/anaconda3/envs/TFM_Project/lib/python3.12', '/opt/anaconda3/envs/TFM_Project/lib/python3.12/lib-dynload', '', '/opt/anaconda3/envs/TFM_Project/lib/python3.12/site-packages', '/Users/jayarza/Developer/Master Data Science/TFM/Proyecto_Git/TFM_GroupC_KS24-25']

In [4]:
import pandas as pd
import pymssql
import credenciales_sqlserver as cred
import utils.tfm_functions_bd_mac as tfbd
import utils.tfm_auxiliar_functions as tfmg

In [5]:
#Primero excluimos los registros que no tienen DISTRITO definido. Son registros de la comunidad de Madrid, pero no de la ciudad de Madrid.add()
#No borramos estos registros, para que el Scrapping no los vuelva a recoger
tfbd.update_processed_with_distrito_not_defined()

In [6]:
df = pd.read_sql_query("SELECT * FROM HOUSES WHERE PROCESSED = 0", tfbd.get_connection())

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/3871675934.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM HOUSES WHERE PROCESSED = 0", tfbd.get_connection())

In [7]:
df

,HOUSE_ID,TITLE,PRICE,ADDRESS1,ADDRESS2,CITY,ENERGY_CONSUME,ENERGY_EMISSION,PLANTA,SUPERFICIE,...,BEDROOMS,BATHROOMS,ARR,PURCHASE_COST,TOTAL_PURCHASE_COST,FIXED_OPEX,VARIABLE_OPEX,ROI,PROCESSED,PER
0,100053144,Piso en venta en calle de Saturno,142000.0,Calle de Saturno,Barrio Casco Histórico de Barajas,"Madrid capital, Madrid",None,None,Planta 1ª,Consumo: \n260 kWh/m² año,...,3,1,29089.38,17040.0,159040.0,4260.0,8726.81,10.12,0,9.88
1,100281275,Chalet adosado en venta en Las Matas- Peñascales,280000.0,Barrio Las Matas- Peñascales,Distrito Las Matas- Peñascales,"Zona noroeste, Madrid",None,None,2 plantas,"Emisiones: \n65,5 kg CO2/m² año",...,3,1,36839.28,33600.0,313600.0,8400.0,11051.78,5.54,0,18.04
2,100445913,Piso en venta en calle Marcelo Usera,259000.0,Calle Marcelo Usera,Barrio Moscardó,"Madrid capital, Madrid",icon-energy-c-f,icon-energy-c-f,None,"73 m² construidos, 67 m² útiles",...,3,1,30473.46,31080.0,290080.0,7770.0,9142.04,4.68,0,21.39
3,100454896,Piso en venta en Fuentes s/n,139900.0,Fuentes s/n,Distrito Noroeste,"Corredor del Henares, Madrid",None,None,Planta 5ª exterior,63 m² construidos,...,3,1,36839.28,16788.0,156688.0,4197.0,11051.78,13.78,0,7.26
4,100519346,Piso en venta en Écija,1649000.0,Écija,Barrio Argüelles,"Madrid capital, Madrid",None,None,Planta 3ª exterior,175 m² construidos,...,3,3,45932.97,197880.0,1846880.0,49470.0,13779.89,-0.94,0,-106.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5727,98948086,Piso en venta en Av. de Abrantes,65000.0,Av. de Abrantes,Barrio Abrantes,"Madrid capital, Madrid",None,None,None,"25 m² construidos, 24 m² útiles",...,1,1,18846.24,7800.0,72800.0,1950.0,5653.87,15.44,0,6.48
5728,99332286,Casa o chalet en venta en calle Ciempozuelos,295000.0,Calle Ciempozuelos,Distrito San Isidro,"Zona sur, Madrid",None,None,None,148 m² construidos,...,4,1,40690.53,35400.0,330400.0,8850.0,12207.16,5.94,0,16.83
5729,99447659,Piso en venta en calle de Ascao,518000.0,Calle de Ascao,Barrio Pueblo Nuevo,"Madrid capital, Madrid",None,None,Planta 1ª,"162 m² construidos, 128 m² útiles",...,4,2,42991.80,62160.0,580160.0,15540.0,12897.54,2.51,0,39.86
5730,99616898,"Piso en venta en calle de Andrés Mellado, 18",480000.0,"Calle de Andrés Mellado, 18",Barrio Gaztambide,"Madrid capital, Madrid",None,None,Planta 4ª interior,"40 m² construidos, 32 m² útiles",...,1,1,25252.35,57600.0,537600.0,14400.0,7575.71,0.61,0,164.07
5731,99951173,"Piso en venta en Margaritas, 55",139000.0,"Margaritas, 55",Barrio Berruguete,"Madrid capital, Madrid",None,None,None,"35 m² construidos, 30 m² útiles",...,1,1,22320.66,16680.0,155680.0,4170.0,6696.20,7.36,0,13.59

In [8]:
df.columns

Index(['HOUSE_ID', 'TITLE', 'PRICE', 'ADDRESS1', 'ADDRESS2', 'CITY',
       'ENERGY_CONSUME', 'ENERGY_EMISSION', 'PLANTA', 'SUPERFICIE',
       'HABITACIONES', 'BANOS', 'GARAJE', 'ESTADO', 'ARMARIOS_EMPOTRADOS',
       'ANO', 'CALEFACCION', 'PISCINA', 'JARDIN', 'UPDATE_DATE', 'URL', 'ZONA',
       'MORE_INFO', 'ASCENSOR', 'MOVILIDAD_REDUCIDA', 'TRASTERO', 'TERRAZA',
       'BALCON', 'AIRE_ACOND', 'ORIENTACION', 'LATITUDE', 'LONGITUDE',
       'CREATED_DATE', 'UPDATED_DATE', 'DISTRITO', 'PRICE_PER_NIGHT',
       'DISTANCE_TO_METRO', 'DISTANCE_TO_CERCANIAS', 'DISTANCE_TO_EMT',
       'DISTANCE_TO_INTERURBANOS', 'DISTANCE_TO_MLO', 'BUILT_AREA', 'BEDROOMS',
       'BATHROOMS', 'ARR', 'PURCHASE_COST', 'TOTAL_PURCHASE_COST',
       'FIXED_OPEX', 'VARIABLE_OPEX', 'ROI', 'PROCESSED', 'PER'],
      dtype='object')

In [9]:
df = df[["HOUSE_ID","DISTRITO","HABITACIONES","BANOS","GARAJE","CALEFACCION","PISCINA","ASCENSOR","MOVILIDAD_REDUCIDA","TERRAZA","BALCON","AIRE_ACOND","LATITUDE","LONGITUDE","DISTANCE_TO_METRO","DISTANCE_TO_CERCANIAS","DISTANCE_TO_EMT","DISTANCE_TO_INTERURBANOS","DISTANCE_TO_MLO"]]

In [10]:
df.columns

Index(['HOUSE_ID', 'DISTRITO', 'HABITACIONES', 'BANOS', 'GARAJE',
       'CALEFACCION', 'PISCINA', 'ASCENSOR', 'MOVILIDAD_REDUCIDA', 'TERRAZA',
       'BALCON', 'AIRE_ACOND', 'LATITUDE', 'LONGITUDE', 'DISTANCE_TO_METRO',
       'DISTANCE_TO_CERCANIAS', 'DISTANCE_TO_EMT', 'DISTANCE_TO_INTERURBANOS',
       'DISTANCE_TO_MLO'],
      dtype='object')

In [11]:
df.head(10)

,HOUSE_ID,DISTRITO,HABITACIONES,BANOS,GARAJE,CALEFACCION,PISCINA,ASCENSOR,MOVILIDAD_REDUCIDA,TERRAZA,BALCON,AIRE_ACOND,LATITUDE,LONGITUDE,DISTANCE_TO_METRO,DISTANCE_TO_CERCANIAS,DISTANCE_TO_EMT,DISTANCE_TO_INTERURBANOS,DISTANCE_TO_MLO
0,100053144,Barajas,3 habitaciones,1 baño,False,None,False,True,Not defined,False,False,False,40.473428,-3.579610,359.0,2346.0,193.0,217.0,6326.0
1,100281275,Centro,3 habitaciones,1 baño,False,Calefacción individual: Gas natural,False,False,Not defined,True,False,False,40.416728,-3.703291,11.0,22.0,218.0,1293.0,6431.0
2,100445913,Usera,3 habitaciones,1 baño,False,Calefacción individual,False,True,Not defined,False,False,False,40.385695,-3.707122,157.0,1040.0,119.0,592.0,5857.0
3,100454896,Centro,3 habitaciones,1 baño,False,Calefacción individual: Gas natural,False,True,Not defined,False,False,False,40.416731,-3.703297,10.0,22.0,219.0,1294.0,6430.0
4,100519346,Moncloa - Aravaca,3 habitaciones,3 baños,False,Calefacción individual,False,True,Not defined,True,False,False,40.431497,-3.723654,525.0,1193.0,89.0,420.0,5603.0
5,100656798,Villaverde,3 habitaciones,1 baño,False,None,False,True,Not defined,False,True,False,40.342226,-3.684312,757.0,42.0,357.0,719.0,9780.0
6,100794368,Usera,3 habitaciones,1 baño,False,None,False,True,Not defined,False,False,False,40.386044,-3.714293,372.0,1547.0,149.0,222.0,5255.0
7,100794996,Usera,3 habitaciones,1 baño,False,None,False,True,Not defined,True,False,False,40.383759,-3.704785,412.0,748.0,90.0,623.0,6099.0
8,100891794,Chamartín,5 habitaciones,5 baños,True,Calefacción central,False,True,1,True,False,False,40.439114,-3.684946,525.0,1043.0,113.0,696.0,4808.0
9,100909239,Vicálvaro,4 habitaciones,3 baños,True,None,False,False,Not defined,True,False,False,40.416709,-3.581269,1210.0,1878.0,1194.0,146.0,9791.0

In [12]:
df.isna().sum()

HOUSE_ID                       0
DISTRITO                       0
HABITACIONES                   0
BANOS                          0
GARAJE                         0
CALEFACCION                 1629
PISCINA                        0
ASCENSOR                       0
MOVILIDAD_REDUCIDA             0
TERRAZA                        0
BALCON                         0
AIRE_ACOND                     0
LATITUDE                       0
LONGITUDE                      0
DISTANCE_TO_METRO              0
DISTANCE_TO_CERCANIAS          0
DISTANCE_TO_EMT                0
DISTANCE_TO_INTERURBANOS       0
DISTANCE_TO_MLO                0
dtype: int64

In [13]:
df["BANOS"].value_counts()

BANOS
1 baño       2707
2 baños      1793
3 baños       677
4 baños       314
5 baños       131
6 baños        61
7 baños        16
8 baños        12
Sin baños       8
9 baños         5
11 baños        3
10 baños        3
16 baños        1
12 baños        1
Name: count, dtype: int64

In [14]:
# dfm = dfm[['bedrooms','bathrooms','price','renta_bin','ascensor','pool','terraza','balcon','distance_to_center','aire_acondicionado','movilidad_reducida','calefaccion','DISTANCE_TO_METRO', 'DISTANCE_TO_CERCANIAS', 'DISTANCE_TO_EMT',
#        'DISTANCE_TO_INTERURBANOS', 'DISTANCE_TO_MLO']]

Tratamiento de la columna HABITACIONES -> bedrooms

In [15]:
df.loc[df["HABITACIONES"] == "Sin habitación", "HABITACIONES"] = "1"

In [16]:
df["bedrooms"] = df["HABITACIONES"].str.replace(" habitaciones", "").str.replace(" habitación", "").astype("int")

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/463132343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bedrooms"] = df["HABITACIONES"].str.replace(" habitaciones", "").str.replace(" habitación", "").astype("int")

In [17]:
df["bedrooms"].value_counts()

bedrooms
3     1992
2     1627
1      928
4      725
5      290
6      101
7       37
8        9
9        7
10       6
11       5
16       2
12       2
14       1
Name: count, dtype: int64

Tratamiento de columna BANOS -> bathrooms

In [18]:
df.loc[df["BANOS"] == "Sin baños", "BANOS"] = "1"

In [19]:
df["bathrooms"] = df["BANOS"].str.replace(" baños", "").str.replace(" baño", "").astype("int")

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/4088328636.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bathrooms"] = df["BANOS"].str.replace(" baños", "").str.replace(" baño", "").astype("int")

In [20]:
df["bathrooms"].value_counts()

bathrooms
1     2715
2     1793
3      677
4      314
5      131
6       61
7       16
8       12
9        5
11       3
10       3
16       1
12       1
Name: count, dtype: int64

Tratamiento de Garaje

In [21]:
df["GARAJE"] = df["GARAJE"].astype(int)

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/393140706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["GARAJE"] = df["GARAJE"].astype(int)

Tratamiento de Calefaccion

In [22]:
df["CALEFACCION"].value_counts()

CALEFACCION
Calefacción individual: Gas natural            1594
Calefacción individual: Eléctrica               554
Calefacción individual                          545
Calefacción central: Gas                        379
Calefacción central                             369
No dispone de calefacción                       342
Calefacción individual: Bomba de frío/calor     215
Calefacción central: Gasoil                      82
Calefacción individual: Gas propano/butano       22
Calefacción individual: Gas                       1
Name: count, dtype: int64

In [23]:
df["CALEFACCION"].fillna(0,inplace=True)

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/4142605454.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["CALEFACCION"].fillna(0,inplace=True)
/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/4142605454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["CALEFACCION"].fillna(0,inplace=True)

In [24]:
df.loc[df["CALEFACCION"] == "No dispone de calefacción", "CALEFACCION"] = 0

In [25]:
df.loc[df["CALEFACCION"] != 0, "CALEFACCION"] = 1

In [26]:
df["CALEFACCION"] = df["CALEFACCION"].astype(int)

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/1271486579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["CALEFACCION"] = df["CALEFACCION"].astype(int)

Tratamiento de piscina

In [27]:
df["PISCINA"] = df["PISCINA"].astype(int)

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/3745167064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["PISCINA"] = df["PISCINA"].astype(int)

Tratamiento de Ascensor

In [28]:
df["ASCENSOR"] = df["ASCENSOR"].astype(int)

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/3302858379.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ASCENSOR"] = df["ASCENSOR"].astype(int)

Tratamiento Movilidad Reducida

In [29]:
df.loc[df["MOVILIDAD_REDUCIDA"] != "1","MOVILIDAD_REDUCIDA"] = 0

In [30]:
df["MOVILIDAD_REDUCIDA"] = df["MOVILIDAD_REDUCIDA"].astype("int")

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/292397912.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["MOVILIDAD_REDUCIDA"] = df["MOVILIDAD_REDUCIDA"].astype("int")

Tratamiento de Terraza, Balcon y Aire Acond

In [31]:
df["TERRAZA"] = df["TERRAZA"].astype("int")
df["BALCON"] = df["BALCON"].astype("int")
df["AIRE_ACOND"] = df["AIRE_ACOND"].astype("int")

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/524440197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["TERRAZA"] = df["TERRAZA"].astype("int")
/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/524440197.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["BALCON"] = df["BALCON"].astype("int")
/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/524440197.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["AIRE_ACOND"] = df["AIRE_ACOND"].astype("int")

Nueva Columna Distance_to_center

In [32]:
center_lat, center_lon = 40.4168, -3.7038

# Create distance to city center
df['distance_to_center'] = np.sqrt((df['LATITUDE'] - center_lat)**2 + (df['LONGITUDE'] - center_lon)**2)

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/554863196.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['distance_to_center'] = np.sqrt((df['LATITUDE'] - center_lat)**2 + (df['LONGITUDE'] - center_lon)**2)

Nueva columna renta_bin

In [33]:
df["DISTRITO"].value_counts()

DISTRITO
Centro                   1607
Salamanca                 622
Carabanchel               322
Chamberí                  298
Ciudad Lineal             272
Puente de Vallecas        256
Tetuán                    234
Chamartín                 215
Latina                    202
Retiro                    197
Arganzuela                196
Fuencarral - El Pardo     173
San Blas - Canillejas     171
Villaverde                170
Hortaleza                 166
Moncloa - Aravaca         144
Vicálvaro                 138
Usera                     134
Villa de Vallecas         106
Moratalaz                  62
Barajas                    47
Name: count, dtype: int64

In [34]:
#Import data from Ayto de Madrid, rentas
df_rentas = tfmg.get_df_rentas()#pd.read_csv('../data_import/ayto_madrid/Datos_Rentas_Madrid_2022.csv',delimiter=";")

In [35]:
df["renta_bin"] = df['DISTRITO'].apply(lambda x: tfmg.get_renta_bin(x, df_rentas))

/var/folders/y1/nqw3rhqs1xv4s4gzlmjk02680000gn/T/ipykernel_6691/1705095733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["renta_bin"] = df['DISTRITO'].apply(lambda x: tfmg.get_renta_bin(x, df_rentas))

In [36]:
df["renta_bin"].value_counts()

renta_bin
bajo        2484
alto        1456
muy_bajo    1190
muy_alto     359
medio        243
Name: count, dtype: int64

In [37]:
df.columns

Index(['HOUSE_ID', 'DISTRITO', 'HABITACIONES', 'BANOS', 'GARAJE',
       'CALEFACCION', 'PISCINA', 'ASCENSOR', 'MOVILIDAD_REDUCIDA', 'TERRAZA',
       'BALCON', 'AIRE_ACOND', 'LATITUDE', 'LONGITUDE', 'DISTANCE_TO_METRO',
       'DISTANCE_TO_CERCANIAS', 'DISTANCE_TO_EMT', 'DISTANCE_TO_INTERURBANOS',
       'DISTANCE_TO_MLO', 'bedrooms', 'bathrooms', 'distance_to_center',
       'renta_bin'],
      dtype='object')

In [38]:
df = df [['HOUSE_ID','GARAJE','CALEFACCION', 'PISCINA', 'ASCENSOR', 'MOVILIDAD_REDUCIDA', 'TERRAZA',
       'BALCON', 'AIRE_ACOND','DISTANCE_TO_METRO',
       'DISTANCE_TO_CERCANIAS', 'DISTANCE_TO_EMT', 'DISTANCE_TO_INTERURBANOS',
       'DISTANCE_TO_MLO', 'bedrooms', 'bathrooms',
       'distance_to_center', 'renta_bin']]

In [39]:
df.rename(columns={'ASCENSOR': 'ascensor',
    'GARAJE': 'garaje',
    'PISCINA': 'pool',
    'CALEFACCION':'calefaccion',
    'TERRAZA': 'terraza',
    'BALCON': 'balcon',
    'MOVILIDAD_REDUCIDA':'movilidad_reducida',
    'AIRE_ACOND':'aire_acondicionado',
    'DISTANCE_TO_METRO':'distance_to_metro',
    'DISTANCE_TO_CERCANIAS':'distance_to_cercanias',
    'DISTANCE_TO_EMT':'distance_to_emt',
    'DISTANCE_TO_INTERURBANOS':'distance_to_interurbanos',
    'DISTANCE_TO_MLO':'distance_to_mlo'},
    inplace = True)

#bedrooms                  12355 non-null  int64  
#bathrooms                 12355 non-null  int64  
#price                     12355 non-null  float64
#renta_bin                 12355 non-null  object 
#ascensor                  12355 non-null  int64  
#garaje                    12355 non-null  int64  
#pool                      12355 non-null  int64  
#terraza                   12355 non-null  int64  
#balcon                    12355 non-null  int64  
#distance_to_center        12355 non-null  float64
#aire_acondicionado        12355 non-null  int64  
#movilidad_reducida        12355 non-null  int64  
#calefaccion               12355 non-null  int64  
#distance_to_metro         12355 non-null  float64
#distance_to_cercanias     12355 non-null  float64
#distance_to_emt           12355 non-null  float64
#distance_to_interurbanos  12355 non-null  float64
#distance_to_mlo           12355 non-null  float64

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5732 entries, 0 to 5731
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   HOUSE_ID                  5732 non-null   object
 1   garaje                    5732 non-null   int64
 2   calefaccion               5732 non-null   int64
 3   pool                      5732 non-null   int64
 4   ascensor                  5732 non-null   int64
 5   movilidad_reducida        5732 non-null   int64
 6   terraza                   5732 non-null   int64
 7   balcon                    5732 non-null   int64
 8   aire_acondicionado        5732 non-null   int64
 9   distance_to_metro         5732 non-null   float64
 10  distance_to_cercanias     5732 non-null   float64
 11  distance_to_emt           5732 non-null   float64
 12  distance_to_interurbanos  5732 non-null   float64
 13  distance_to_mlo           5732 non-null   float64
 14  bedrooms                  5732 non-null   int64
 15  bathrooms                 5732 non-null   int64
 16  distance_to_center        5732 non-null   float64
 17  renta_bin                 5732 non-null   object
dtypes: float64(6), int64(10), object(2)
memory usage: 806.2+ KB

In [41]:
df.head(20)

,HOUSE_ID,garaje,calefaccion,pool,ascensor,movilidad_reducida,terraza,balcon,aire_acondicionado,distance_to_metro,distance_to_cercanias,distance_to_emt,distance_to_interurbanos,distance_to_mlo,bedrooms,bathrooms,distance_to_center,renta_bin
0,100053144,0,0,0,1,0,0,0,0,359.0,2346.0,193.0,217.0,6326.0,3,1,0.136491,medio
1,100281275,0,1,0,0,0,1,0,0,11.0,22.0,218.0,1293.0,6431.0,3,1,0.000515,bajo
2,100445913,0,1,0,1,0,0,0,0,157.0,1040.0,119.0,592.0,5857.0,3,1,0.031282,muy_bajo
3,100454896,0,1,0,1,0,0,0,0,10.0,22.0,219.0,1294.0,6430.0,3,1,0.000508,bajo
4,100519346,0,1,0,1,0,1,0,0,525.0,1193.0,89.0,420.0,5603.0,3,3,0.024702,muy_alto
5,100656798,0,0,0,1,0,0,1,0,757.0,42.0,357.0,719.0,9780.0,3,1,0.077079,muy_bajo
6,100794368,0,0,0,1,0,0,0,0,372.0,1547.0,149.0,222.0,5255.0,3,1,0.032497,muy_bajo
7,100794996,0,0,0,1,0,1,0,0,412.0,748.0,90.0,623.0,6099.0,3,1,0.033056,muy_bajo
8,100891794,1,1,0,1,1,1,0,0,525.0,1043.0,113.0,696.0,4808.0,5,5,0.029213,muy_alto
9,100909239,1,0,0,0,0,1,0,0,1210.0,1878.0,1194.0,146.0,9791.0,4,3,0.122531,bajo
10,100934265,0,1,0,1,1,1,0,0,350.0,1132.0,172.0,1449.0,3881.0,3,1,0.038864,bajo
11,100961223,0,1,0,1,1,0,0,0,449.0,1088.0,73.0,448.0,5027.0,2,1,0.026216,muy_bajo
12,101141691,0,1,0,1,0,1,0,0,365.0,878.0,29.0,1701.0,2142.0,3,1,0.049145,muy_bajo
13,101156711,0,0,0,0,0,0,0,0,11.0,22.0,218.0,1293.0,6431.0,5,3,0.000515,bajo
14,101203668,0,1,0,1,0,0,0,0,109.0,1408.0,94.0,824.0,4449.0,3,1,0.030088,muy_bajo
15,101219531,0,1,0,1,0,0,0,0,372.0,446.0,134.0,801.0,2852.0,3,1,0.042543,muy_bajo
16,101244643,0,1,0,1,0,1,0,0,327.0,1633.0,84.0,1381.0,6058.0,3,2,0.033172,alto
17,101350775,0,1,0,1,0,0,0,0,11.0,22.0,218.0,1293.0,6431.0,2,1,0.000515,bajo
18,101385771,0,1,0,1,0,0,0,0,175.0,1277.0,91.0,1740.0,5819.0,1,1,0.017638,alto
19,101391795,0,0,0,1,0,0,0,0,390.0,1262.0,91.0,366.0,4515.0,1,1,0.033950,muy_alto